from django.urls import re_path

from plugins.consortial_billing import views

urlpatterns = [
    re_path(
        r'^$',
        views.supporters,
        name='public_supporter_list',
    ),
    re_path(
        r'^manager/$',
        views.manager,
        name='supporters_manager',
    ),
    re_path(
        r'^site/(?P<page_name>.*)/$',
        views.view_custom_page,
        name='supporters_custom_page',
    ),
    re_path(
        r'^signup/$',
        views.signup,
        name='supporter_signup',
    ),
    re_path(
        r'^search/$',
        views.SupporterList.as_view(),
        name='supporter_list',
    ),
    re_path(
        r'^new-supporter/$',
        views.edit_supporter_band,
        name='new_supporter',
    ),
    re_path(
        r'^edit-supporter-band/(?P<supporter_id>\d+)/$',
        views.edit_supporter_band,
        name='edit_supporter_band',
    ),
    re_path(
        r'^recommend-us/$',
        views.recommend_us,
        name='recommend_us',
    ),
    re_path(
        r'^recommend-us/see-matching-supporters/$',
        views.recommend_us_see_matching_supporters,
        name='recommend_us_see_matching_supporters',
    ),
    re_path(
        r'^recommend-us/choose-role/$',
        views.recommend_us_choose_role,
        name='recommend_us_choose_role',
    ),
    re_path(
        r'^recommend-us/search-article/$',
        views.recommend_us_search_article,
        name='recommend_us_search_article',
    ),
    re_path(
        r'^recommend-us/search-journal/$',
        views.recommend_us_search_journal,
        name='recommend_us_search_journal',
    ),
    re_path(
        r'^recommend-us/choose-article/$',
        views.recommend_us_choose_article,
        name='recommend_us_choose_article',
    ),
    re_path(
        r'^recommend-us/choose-journal/$',
        views.recommend_us_choose_journal,
        name='recommend_us_choose_journal',
    ),
    re_path(
        r'^recommend-us/generate-email/$',
        views.recommend_us_generate_email,
        name='recommend_us_generate_email',
    ),
    re_path(
        r'^recommend-us/confirm-sent/$',
        views.recommend_us_confirm_sent,
        name='recommend_us_confirm_sent',
    ),
]
