# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consortial-billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('default_price', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('consortial_billing', models.BooleanField(default=False)),
                ('banding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial-billing.Banding')),
            ],
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial-billing.Institution')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
