# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0002_excludeduser'),
        ('consortial_billing', '0003_auto_20170510_1301'),
    ]

    operations = [
    ]
