# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0006_auto_20170510_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
