# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0007_auto_20170510_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banding',
            name='default_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
