# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0008_auto_20170510_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
