# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0012_auto_20170510_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=500)),
                ('institution', models.CharField(max_length=500)),
                ('address', models.TextField(max_length=500)),
                ('public', models.BooleanField()),
                ('billing_agent_member', models.BooleanField()),
                ('fte', models.TextField(max_length=500)),
                ('other_amount', models.IntegerField(default=0, null=True)),
                ('years', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='banding',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
