# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-11 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0013_auto_20170511_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='banding',
            name='billing_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.BillingAgent'),
        ),
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.TextField(max_length=255, null=True, verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='institution',
            name='email_address',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(max_length=255, null=True, verbose_name='Post/Zip Code'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Institution Name'),
        ),
    ]
