# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-12 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0015_renewal_billing_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='date_renewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
