# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0017_option_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncreaseOptionBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_increase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('banding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.Banding')),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='price_per_band_increase',
        ),
        migrations.AddField(
            model_name='increaseoptionband',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.Option'),
        ),
    ]
