# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0018_auto_20170516_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aye', models.ManyToManyField(related_name='vote_aye', to='consortial_billing.Option')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.Institution')),
                ('no', models.ManyToManyField(related_name='vote_no', to='consortial_billing.Option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.Poll')),
            ],
        ),
    ]
