# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0019_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='all',
            field=models.BooleanField(default=False),
        ),
    ]
