# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0022_poll_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='banding',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
