# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0023_banding_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Billing Address'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Post/Zip Code'),
        ),
    ]
