# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-20 10:39
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import plugins.consortial_billing.models


class Migration(migrations.Migration):

    def forward_func(apps, schema_editor):
        #plugins.consortial_billing.models.Institution
        Institution = apps.get_model('consortial_billing', 'Institution')
        db_alias = schema_editor.connection.alias

        for institution in Institution.objects.using(db_alias).all():
            institution.sort_country = institution.country.replace('The ', '')
            institution.save()


    def reverse_func(apps, schema_editor):
        pass

    dependencies = [
        ('consortial_billing', '0024_auto_20170607_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('country', 'name')},
        ),
        migrations.AddField(
            model_name='institution',
            name='sort_country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='banding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consortial_billing.Banding'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='billing_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consortial_billing.BillingAgent'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='consortium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consortial_billing.Institution'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/martin/Documents/Programming/janeway/src/media'), upload_to=plugins.consortial_billing.models.file_upload_path),
        ),
        migrations.RunPython(forward_func, reverse_func)
    ]
