# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-21 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0025_auto_20170619_1413'),
        ('consortial_billing', '0025_auto_20170620_1039'),
    ]

    operations = [
    ]
