# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-26 17:17
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import plugins.consortial_billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0027_auto_20170622_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banding',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Institution Name'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/Mounts/TERA1/Documents/Programming/janeway/src/media'), upload_to=plugins.consortial_billing.models.file_upload_path),
        ),
    ]
