# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-26 10:46
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import plugins.consortial_billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0028_auto_20170626_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='poll',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/ajrbyers/code/janeway/src/media'), upload_to=plugins.consortial_billing.models.file_upload_path),
        ),
    ]
