# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0032_auto_20180226_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='institution',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='referral',
            name='new_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_institution', to='consortial_billing.Institution'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referring_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referring_institution', to='consortial_billing.Institution'),
        ),
    ]
