# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0035_auto_20180228_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='banding',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=20),
        ),
    ]
