# Generated by Django 3.2.16 on 2022-12-16 13:29

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import plugins.consortial_billing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consortial_billing', '0038_auto_20190823_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banding',
            name='billing_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consortial_billing.billingagent'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='supporter_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consortial_billing.supportlevel'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/ajrbyers/Code/janeway/src/media'), upload_to=plugins.consortial_billing.models.file_upload_path),
        ),
        migrations.AlterField(
            model_name='poll',
            name='staffer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
