# Generated by Django 3.2.18 on 2023-04-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0042_clean_up_data_model_20230409_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='fixed_fee',
            field=models.BooleanField(
                default=False,
                help_text='Select if you want to manually set the fee '
                          'for this band. The fee calculator for this '
                          'band (i.e., this combination of size, level, '
                          'country, and currency) will then return '
                          'whatever fee you type in the fee field. '
                          'Note: the field has no effect on base bands, '
                          'which do take a manually input fee.',
            ),
        ),
    ]
