# Generated by Django 3.2.18 on 2023-04-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0043_band_fixed_fee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'get_latest_by': 'datetime'},
        ),
        migrations.AlterField(
            model_name='supportersize',
            name='name',
            field=models.CharField(
                help_text='The name of the size band, '
                          'e.g. Large Institution',
                max_length=50,
            ),
        ),
    ]
