# Generated by Django 3.2.18 on 2023-10-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0045_level_multiplier_to_order_20231011_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, help_text='Currency symbol, e.g. €', max_length=2),
        ),
    ]
