# Generated by Django 3.2.18 on 2024-02-12 17:04

from django.db import migrations, models


def store_empty_string(apps, schema_editor):
    BillingAgent = apps.get_model('consortial_billing', 'BillingAgent')
    BillingAgent.objects.filter(redirect_url__isnull=True).update(redirect_url='')
    Supporter = apps.get_model('consortial_billing', 'Supporter')
    Supporter.objects.filter(address__isnull=True).update(address='')
    Supporter.objects.filter(postal_code__isnull=True).update(postal_code='')
    SupportLevel = apps.get_model('consortial_billing', 'SupportLevel')
    SupportLevel.objects.filter(name__isnull=True).update(name='')


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0049_alter_supportersize_multiplier'),
    ]

    operations = [
        migrations.RunPython(
            store_empty_string,
            reverse_code=migrations.RunPython.noop
        ),
    ]
