# Generated by Django 3.2.18 on 2024-02-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0050_store_empty_strings_20240212_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingagent',
            name='redirect_url',
            field=models.URLField(
                blank=True,
                default='',
                help_text='If populated, the user will be redirected here to '
                          'complete the sign-up process'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supporter',
            name='address',
            field=models.TextField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='Billing address',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supporter',
            name='postal_code',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportlevel',
            name='name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='The level of support, e.g. Standard or Gold',
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
