# Generated by Django 3.2.20 on 2024-03-06 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_agent_contacts(apps, schema_editor):
    BillingAgent = apps.get_model('consortial_billing', 'BillingAgent')
    AgentContact = apps.get_model('consortial_billing', 'AgentContact')
    for agent in BillingAgent.objects.all():
        for account in agent.users.all():
            AgentContact.objects.create(agent=agent, account=account)


def move_supporter_contacts(apps, schema_editor):
    Supporter = apps.get_model('consortial_billing', 'Supporter')
    SupporterContact = apps.get_model('consortial_billing', 'SupporterContact')
    for supporter in Supporter.objects.all():
        for account in supporter.contacts.all():
            SupporterContact.objects.create(supporter=supporter, account=account)


def move_old_bands(apps, schema_editor):
    Supporter = apps.get_model('consortial_billing', 'Supporter')
    OldBand = apps.get_model('consortial_billing', 'OldBand')
    for supporter in Supporter.objects.all():
        for band in supporter.old_bands.all():
            OldBand.objects.create(supporter=supporter, band=band)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consortial_billing', '0051_auto_20240212_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.billingagent')),
            ],
        ),
        migrations.RunPython(
            move_agent_contacts,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='billingagent',
            name='users',
        ),
        migrations.CreateModel(
            name='SupporterContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.supporter')),
            ],
        ),
        migrations.RunPython(
            move_supporter_contacts,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='contacts',
        ),
        migrations.CreateModel(
            name='OldBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.band')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consortial_billing.supporter')),
            ],
        ),
        migrations.RunPython(
            move_old_bands,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='old_bands',
        ),
    ]
