# Generated by Django 3.2.20 on 2024-04-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0052_auto_20240306_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='prospective_band',
            field=models.ForeignKey(blank=True, help_text='Prospective band', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospective_supporter', to='consortial_billing.band'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='band',
            field=models.ForeignKey(blank=True, help_text='Current band', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_supporter', to='consortial_billing.band'),
        ),
    ]
