# Generated by Django 3.2.20 on 2024-04-24 14:10

from copy import copy

from django.db import migrations, models

# About this migration: the fixed_fee attribute was half a solution.
# The full solution implemented here is to reframe the booleans "fixed_fee"
# and "base", along with an unstated default attribute "calculated", into
# a simple "category" field that can be used to control how the band behaves.

def migrate_base_to_category(apps, schema_editor):
    Band = apps.get_model('consortial_billing', 'Band')
    for base_band in Band.objects.filter(base=True):
        base_band.category = 'base'
        base_band.save()


def migrate_fixed_to_category(apps, schema_editor):
    # Why are fixed-fee bands being set as calculated here?
    # Fixed fees were previously set for individual countries.
    # Going forward, base levels can be set by country
    # (in addition to support level, introduced earlier).
    # So one old fixed-fee band is equivalent to a combination of
    # a base band for that country
    # plus calculated bands dependent on it.
    Band = apps.get_model('consortial_billing', 'Band')
    for band in Band.objects.filter(fixed_fee=True):
        new_base_band = copy(band)
        new_base_band.pk = None
        new_base_band.category = 'base'
        new_base_band.save()
        band.category = 'calculated'
        band.save()


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0053_prospective_band_20240419_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='category',
            field=models.CharField(
                choices=[
                    ('calculated','Calculated'),
                    ('special','Special'),
                    ('base','Base')
                ],
                default='calculated',
                help_text="Controls how the band functions, either as the basis "
                  "or result of fee calculation, or as a special band "
                  "for one supporter with a manually set fee.",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            migrate_base_to_category,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            migrate_fixed_to_category,
            reverse_code=migrations.RunPython.noop
        ),
    ]
