# Generated by Django 3.2.20 on 2024-04-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0054_band_category_20240424_1510'),
    ]

    operations = [
    ]
