# Generated by Django 3.2.20 on 2024-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0055_remove_deprecated_band_fields_20240424_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter',
            name='country',
        ),
    ]
