# Generated by Django 4.2.15 on 2024-10-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consortial_billing', '0056_remove_supporter_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='base',
            field=models.BooleanField(
                default=False,
                help_text='Deprecated. '
                          'Select if this is the base band to represent '
                          'the base fee, country, and currency for a '
                          'given support level.',
                ),
        ),
        migrations.AlterField(
            model_name='band',
            name='display',
            field=models.BooleanField(
                default=True,
                help_text='Deprecated. ',
            ),
        ),
        migrations.AlterField(
            model_name='band',
            name='fixed_fee',
            field=models.BooleanField(
                default=False,
                help_text='Deprecated. '
                          'Select if you want to manually set the fee '
                          'for this band. The fee calculator for this '
                          'band (i.e., this combination of size, level, '
                          'country, and currency) will then return '
                          'whatever fee you type in the fee field. '
                          'Note: thie field has no effect on base bands, '
                          'which do take a manually input fee.',
                ),
        ),
    ]
